name: Enforce Commit Message

on:
  push:
    branches:
      - tree

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate commit messages
        run: |
          if ! git log -1 --pretty=%B | grep -q "this is my commit"; then
            echo "Commit message must include 'this is my commit'"
            exit 1
          fi
